METHOD: "api"
DATASET: "ckt"
GRAMMAR: "ednce"
SUFFIX: "" # suffix for log filepath, for concurrent runs

MODEL: "gpt-4o"
FILE_NAME: "data/api_ckt_ednce.txt"
IMG_DIR: "data/api_ckt_ednce/"
CACHE_DIR: "cache/api_ckt_ednce/"

NUM_THREADS: 1
NUM_PROCS: 100
UPDATE_GRAPH_MP: True
VISUALIZE: True
VERBOSE: True
CACHE: False
MAX_TRIES: 10

# EDNCE parameters
CACHE_SUBG: True
LINEAR: True # at most 1 nt per comp, and subgraph must contain nt if present
RESTRICT_POSS_DIRS: True # direction of neighbors limited (tradeoff expressivity vs efficiency)
MIN_EMBEDDING: False # take the minimum or maximum embedding for each rule
LIMIT_FOR_GREEDY: 1000
NUM_RANDOM_SEARCH_TRIES: 10
LIMIT_FOR_DYNAMIC: 5000

# motif args
MAX_NUM_COMPS_FOR_MOTIF_MINING: 5000
MOTIF_MIN_SIZE: 2
MOTIF_MAX_SIZE: 5
NUM_MOTIFS: 10

TOP_DIFF: 30
SEED: 5
NUM_ATTEMPTS: 1

# VISUALIZATION
SCALE: 5
DIM_SCALE: 7.5
NODE_SIZE: 4000
EDGE_THICKNESS: 2
ARROW_SIZE: 20
RULE_SCALE: 5
RULE_NODE_SIZE: 500
RULE_FONT_SIZE: 10
FONT_SIZE: 20
MAX_SIZE: 3000 * 3000 * 4
LAYOUT: "kamada_kawai_layout"
# LAYOUT: 'spring_layout'
TITLE_FONT_SIZE: 50
PARTITION_SIZE: 50
PARTITION_SCALE: 5
POS_EPSILON: 1
PARTITION_NODE_SIZE: 500
MAX_IMAGES: 5
NUM_COMPONENT_SAMPLES_FOR_MOTIFS: 5
NUM_PARTITON_SAMPLES_FOR_MOTIFS: 5

RADIUS: 1
# CMAP_NAME: 'twilight'
# CMAP_NAME: 'twilight'

### CKT
TERMS:
  - yellow
  - lawngreen
  - cyan
  - lightblue
  - deepskyblue
  - dodgerblue
  - silver
  - lightgrey
  - orchid
  - pink

NONTERMS:
  - gray
  - black  # assumes last one is init symbol S

NONFINAL:
  - gray

FINAL:
  - black

LOOKUP:
  R: yellow
  C: lawngreen
  +gm+: cyan
  -gm+: lightblue
  +gm-: deepskyblue
  -gm-: dodgerblue
  sudo_in: silver
  sudo_out: lightgrey
  input: orchid
  output: pink

INVERSE_LOOKUP:
  yellow: R
  lawngreen: C
  cyan: +gm+
  lightblue: -gm+
  deepskyblue: +gm-
  dodgerblue: -gm-
  silver: sudo_in
  lightgrey: sudo_out
  orchid: input
  pink: output