METHOD: "api"
DATASET: "ckt"
GRAMMAR: "ednce"
SUFFIX: "_ablation_2" # suffix for log filepath, for concurrent runs

MODEL: "gpt-4o"
FILE_NAME: "data/api_ckt_ablation_2_ednce.txt"
IMG_DIR: "data/api_ckt_ablation_2_ednce/"
CACHE_DIR: "cache/api_ckt_ablation_2_ednce/"

NUM_THREADS: 1
NUM_PROCS: 100
UPDATE_GRAPH_MP: False
COMPRESS: True
COMPRESS_RULE_MP: True
VISUALIZE: False
VERBOSE: True
CACHE: False
MAX_TRIES: 10

# EDNCE parameters
CACHE_SUBG: True
LINEAR: True # at most 1 nt per comp, and subgraph must contain nt if present
RESTRICT_POSS_DIRS: False # direction of neighbors limited (tradeoff expressivity vs efficiency)
MIN_EMBEDDING: False # take the minimum or maximum embedding for each rule
LIMIT_FOR_GREEDY: 1000
NUM_RANDOM_SEARCH_TRIES: 10
LIMIT_FOR_DYNAMIC: 5000
SUBG_ISO_BATCH_SIZE: 10

# motif args
MAX_NUM_COMPS_FOR_MOTIF_MINING: 5000
MOTIF_MIN_SIZE: 2
MOTIF_MAX_SIZE: 5
NUM_MOTIFS: 1

TOP_DIFF: 30
SEED: 5
NUM_ATTEMPTS: 1

# VISUALIZATION
SCALE: 5
DIM_SCALE: 7.5
NODE_SIZE: 4000
EDGE_THICKNESS: 2
ARROW_SIZE: 20
RULE_SCALE: 5
RULE_NODE_SIZE: 500
RULE_FONT_SIZE: 10
FONT_SIZE: 20
MAX_SIZE: 3000 * 3000 * 4
LAYOUT: "kamada_kawai_layout"
# LAYOUT: 'spring_layout'
TITLE_FONT_SIZE: 50
PARTITION_SIZE: 50
PARTITION_SCALE: 5
POS_EPSILON: 1
PARTITION_NODE_SIZE: 500
MAX_IMAGES: 5
NUM_COMPONENT_SAMPLES_FOR_MOTIFS: 5
NUM_PARTITON_SAMPLES_FOR_MOTIFS: 5

RADIUS: 1
# CMAP_NAME: 'twilight'
# CMAP_NAME: 'twilight'

### CKT
TERMS:
  - yellow
  - lawngreen
  - cyan
  - lightblue
  - deepskyblue
  - dodgerblue
  - silver
  - lightgrey
  - orchid
  - pink

NONTERMS:
  - gray
  - black  # assumes last one is init symbol S

NONFINAL:
  - gray

FINAL:
  - black

LOOKUP:
  R: yellow
  C: lawngreen
  +gm+: cyan
  -gm+: lightblue
  +gm-: deepskyblue
  -gm-: dodgerblue
  sudo_in: silver
  sudo_out: lightgrey
  input: orchid
  output: pink

INVERSE_LOOKUP:
  yellow: R
  lawngreen: C
  cyan: +gm+
  lightblue: -gm+
  deepskyblue: +gm-
  dodgerblue: -gm-
  silver: sudo_in
  lightgrey: sudo_out
  orchid: input
  pink: output


NODE_TYPE:
  R: 0
  C: 1
  +gm+: 2
  -gm+: 3
  +gm-: 4
  -gm-: 5
  sudo_in: 6
  sudo_out: 7
  In: 8
  Out: 9

# needed for subg-based conversion
SUBG_NODE:
  0: ['In']
  1: ['Out']
  2: ['R']
  3: ['C']
  4: ['R', 'C']
  5: ['R', 'C']
  6: ['+gm+']
  7: ['-gm+']
  8: ['+gm-']
  9: ['-gm-']
  10: ['C', '+gm+']
  11: ['C', '-gm+']
  12: ['C', '+gm-']
  13: ['C', '-gm-']
  14: ['R', '+gm+']
  15: ['R', '-gm+']
  16: ['R', '+gm-']
  17: ['R', '-gm-']
  18: ['C', 'R', '+gm+']
  19: ['C', 'R', '-gm+']
  20: ['C', 'R', '+gm-']
  21: ['C', 'R', '-gm-']
  22: ['C', 'R', '+gm+']
  23: ['C', 'R', '-gm+']
  24: ['C', 'R', '+gm-']
  25: ['C', 'R', '-gm-']

SUBG_CON:
  0: null
  1: null
  2: null
  3: null
  4: "series"
  5: "parral"
  6: null
  7: null
  8: null
  9: null
  10: "parral"
  11: "parral"
  12: "parral"
  13: "parral"
  14: "parral"
  15: "parral"
  16: "parral"
  17: "parral"
  18: "parral"
  19: "parral"
  20: "parral"
  21: "parral"
  22: "series"
  23: "series"
  24: "series"
  25: "series"