METHOD: "api"
DATASET: "ckt"
GRAMMAR: "ednce"
SUFFIX: "" # suffix for log filepath, for concurrent runs

MODEL: "gpt-4o"
FILE_NAME: "data/api_ckt_ednce.txt"
IMG_DIR: "data/api_ckt_ednce/"
CACHE_DIR: "cache/api_ckt_ednce/"

NUM_THREADS: 1
NUM_PROCS: 100
VISUALIZE: False
VERBOSE: True
CACHE: False
MAX_TRIES: 10

# EDNCE parameters
CACHE_SUBG: True
LINEAR: True # at most 1 nt per comp, and subgraph must contain nt if present
MIN_EMBEDDING: False # take the minimum or maximum embedding for each rule
LIMIT_FOR_GREEDY: 1000
NUM_RANDOM_SEARCH_TRIES: 10
LIMIT_FOR_DYNAMIC: 5000

# motif args
MAX_NUM_COMPS_FOR_MOTIF_MINING: 5000
MOTIF_MIN_SIZE: 2
MOTIF_MAX_SIZE: 5

TOP_DIFF: 30
SEED: 5
NUM_ATTEMPTS: 1

# VISUALIZATION
SCALE: 5
DIM_SCALE: 7.5
NODE_SIZE: 4000
EDGE_THICKNESS: 2
ARROW_SIZE: 20
RULE_SCALE: 5
RULE_NODE_SIZE: 500
RULE_FONT_SIZE: 10
FONT_SIZE: 20
MAX_SIZE: 3000 * 3000 * 4
LAYOUT: "kamada_kawai_layout"
# LAYOUT: 'spring_layout'
TITLE_FONT_SIZE: 50
PARTITION_SIZE: 50
PARTITION_SCALE: 5
POS_EPSILON: 1
PARTITION_NODE_SIZE: 500
MAX_IMAGES: 5
NUM_COMPONENT_SAMPLES_FOR_MOTIFS: 5
NUM_PARTITON_SAMPLES_FOR_MOTIFS: 5

RADIUS: 1
# CMAP_NAME: 'twilight'
# CMAP_NAME: 'twilight'

### CKT (with basis)
TERMS:
  - orchid
  - pink
  - yellow
  - lawngreen
  - greenyellow
  - yellowgreen
  - cyan
  - lightblue
  - deepskyblue
  - dodgerblue
  - lime
  - seagreen
  - springgreen
  - limegreen
  - lightcoral
  - coral
  - salmon
  - red
  - darkorange
  - bisque
  - navajowhite
  - orange
  - plum
  - violet
  - mediumpurple
  - blueviolet

NONTERMS:
  - gray
  - black

NONFINAL:
  - gray

FINAL:
  - black

LOOKUP:
  input: orchid
  output: pink
  R: yellow
  C: lawngreen
  R serie C: greenyellow
  R paral C: yellowgreen
  +gm+: cyan
  -gm+: lightblue
  +gm-: deepskyblue
  -gm-: dodgerblue
  C paral +gm+: lime
  C paral -gm+: seagreen
  C paral +gm-: springgreen
  C paral -gm-: limegreen
  R paral +gm+: lightcoral
  R paral -gm+: coral
  R paral +gm-: salmon
  R paral gm-: red
  R paral C paral +gm+: darkorange
  R paral C paral -gm+: bisque
  R paral C paral +gm-: navajowhite
  R paral C paral -gm-: orange
  R serie C serie +gm+: plum
  R serie C serie -gm+: violet
  R serie C serie +gm-: mediumpurple
  R serie C serie -gm-: blueviolet
  
INVERSE_LOOKUP:
  orchid: input
  pink: output
  yellow: R
  lawngreen: C
  greenyellow: R serie C
  yellowgreen: R paral C
  cyan: +gm+
  lightblue: -gm+
  deepskyblue: +gm-
  dodgerblue: -gm-
  lime: C paral +gm+
  seagreen: C paral -gm+
  springgreen: C paral +gm-
  limegreen: C paral -gm-
  lightcoral: R paral +gm+
  coral: R paral -gm+
  salmon: R paral +gm-
  red: R paral gm-
  darkorange: R paral C paral +gm+
  bisque: R paral C paral -gm+
  navajowhite: R paral C paral +gm-
  orange: R paral C paral -gm-
  plum: R serie C serie +gm+
  violet: R serie C serie -gm+
  mediumpurple: R serie C serie +gm-
  blueviolet: R serie C serie -gm-


NODE_TYPE:
  R: 0
  C: 1
  +gm+: 2
  -gm+: 3
  +gm-: 4
  -gm-: 5
  sudo_in: 6
  sudo_out: 7
  In: 8
  Out: 9

SUBG_NODE:
  0: ['In']
  1: ['Out']
  2: ['R']
  3: ['C']
  4: ['R', 'C']
  5: ['R', 'C']
  6: ['+gm+']
  7: ['-gm+']
  8: ['+gm-']
  9: ['-gm-']
  10: ['C', '+gm+']
  11: ['C', '-gm+']
  12: ['C', '+gm-']
  13: ['C', '-gm-']
  14: ['R', '+gm+']
  15: ['R', '-gm+']
  16: ['R', '+gm-']
  17: ['R', '-gm-']
  18: ['C', 'R', '+gm+']
  19: ['C', 'R', '-gm+']
  20: ['C', 'R', '+gm-']
  21: ['C', 'R', '-gm-']
  22: ['C', 'R', '+gm+']
  23: ['C', 'R', '-gm+']
  24: ['C', 'R', '+gm-']
  25: ['C', 'R', '-gm-']

SUBG_CON:
  0: null
  1: null
  2: null
  3: null
  4: "series"
  5: "parral"
  6: null
  7: null
  8: null
  9: null
  10: "parral"
  11: "parral"
  12: "parral"
  13: "parral"
  14: "parral"
  15: "parral"
  16: "parral"
  17: "parral"
  18: "parral"
  19: "parral"
  20: "parral"
  21: "parral"
  22: "series"
  23: "series"
  24: "series"
  25: "series"