METHOD: "api"
DATASET: "bn"
GRAMMAR: "ednce"
SUFFIX: "" # suffix for log filepath, for concurrent runs

MODEL: "gpt-4o"
FILE_NAME: "data/api_bn_ednce.txt"
IMG_DIR: "data/api_bn_ednce/"
CACHE_DIR: "cache/api_bn_ednce/"

NUM_THREADS: 1
NUM_PROCS: 100
VISUALIZE: False
VERBOSE: True
CACHE: False
MAX_TRIES: 10

# EDNCE parameters
CACHE_SUBG: True
LINEAR: True # at most 1 nt per comp, and subgraph must contain nt if present
MIN_EMBEDDING: False # take the minimum or maximum embedding for each rule
LIMIT_FOR_GREEDY: 1000
NUM_RANDOM_SEARCH_TRIES: 10
LIMIT_FOR_DYNAMIC: 5000

# motif args
MAX_NUM_COMPS_FOR_MOTIF_MINING: 5000
MOTIF_MIN_SIZE: 2
MOTIF_MAX_SIZE: 5

TOP_DIFF: 30
SEED: 5
NUM_ATTEMPTS: 1

# VISUALIZATION
SCALE: 5
DIM_SCALE: 7.5
NODE_SIZE: 4000
EDGE_THICKNESS: 2
ARROW_SIZE: 20
RULE_SCALE: 5
RULE_NODE_SIZE: 500
RULE_FONT_SIZE: 10
FONT_SIZE: 20
MAX_SIZE: 3000 * 3000 * 4
LAYOUT: "kamada_kawai_layout"
# LAYOUT: 'spring_layout'
TITLE_FONT_SIZE: 50
PARTITION_SIZE: 50
PARTITION_SCALE: 5
POS_EPSILON: 1
PARTITION_NODE_SIZE: 500
MAX_IMAGES: 5
NUM_COMPONENT_SAMPLES_FOR_MOTIFS: 5
NUM_PARTITON_SAMPLES_FOR_MOTIFS: 5

RADIUS: 1
# CMAP_NAME: 'twilight'
# CMAP_NAME: 'twilight'

### HOUSE
TERMS: ["cyan"]
NONTERMS: ["gray", "black"]
NONFINAL: ["gray", "black"]
FINAL: ["red", "blue", "green"]